### PR TITLE
Warning fix

### LINKED ISSUE #366: handle build warnings
The VS/Windows build shows a number of warnings:
- warning C4316, 20
- warning C4018, 25
- warning LNK4221, 4

All warnings need to be addressed.
Double check Linux and macOS.

### PR DESCRIPTION
**Pull request by syncle**
Removes warnings in color map optimization.

Partly resolves #366.

### CODE REVIEW

File: src/Core/ColorMap/ColorMapOptimization.cpp [hunk 1]
```diff
@@ -341,14 +344,16 @@ void OptimizeImageCoorNonrigid(
...
-                float vv = uuvv(1);
+                double uu = uuvv(0);
+                double vv = uuvv(1);
                 if (!images_gray[i]->TestImageBoundary(uu, vv,
                         IMAGE_BOUNDARY_MARGIN))
                     continue;
-                double gray = *PointerAt<float>(*images_gray[i], uu, vv);
-                Eigen::Vector2d dIdf(*PointerAt<float>(*images_dx[i], uu, vv),
-                        *PointerAt<float>(*images_dy[i], uu, vv));
+				bool valid; double gray, dIdfx, dIdfy;
```
Comment (qianyizh) [inline src/Core/ColorMap/ColorMapOptimization.cpp]: indent?

File: src/Core/ColorMap/ColorMapOptimization.cpp [hunk 2]
```diff
@@ -485,16 +490,17 @@ void OptimizeImageCoorRigid(
...
                 Eigen::Vector4d L = intr * G;
-                float u = L(0) / L(2);
-                float v = L(1) / L(2);
+                double u = L(0) / L(2);
+                double v = L(1) / L(2);
                 if (!images_gray[i]->TestImageBoundary(u, v,
                         IMAGE_BOUNDARY_MARGIN))
                     continue;
-                double gray = *PointerAt<float>(*images_gray[i], u, v);
+				bool valid; double gray, dIdx, dIdy;
```
Comment (qianyizh) [inline src/Core/ColorMap/ColorMapOptimization.cpp]: indent?

**Comment by qianyizh** [comment]
It is ready once CIs pass.
