### PR TITLE
Instruction for Python packages

### LINKED ISSUE #222: Python dependencies
I suppose most python users will have things like matplotlib already installed, but following a fresh build following the documentation instructions I immediately got an error running `python rgbd_redwood.py`:

```
Traceback (most recent call last):
  File "rgbd_redwood.py", line 10, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
```

I'm not sure if matplotlib is the only python package I'm missing.

I'd like to request a python dependency check/script like the `scripts/install-deps-osx.sh`.  

(I fixed this particular issue with `pip install matplotlib`)

### PR DESCRIPTION
**Pull request by syncle**
This PR resolves #222.
I modified instruction a bit and added text file: scripts/install-deps-python.txt. The text file is for users to choose one of the available options.

### CODE REVIEW

**Comment by qianyizh** [comment]
Can you change it to .sh?

File: scripts/install-deps-python.sh [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+# - matplotlib
+# - opencv
+
+# To install these package, try one of the following
+while true; do
+	read -p "Install Python dependencies using pip or conda? (p: pip, c: conda, q: quit) : " pcq
+	    case $pcq in
+			[Pp]* )
+			# for pip users
+	        python -m pip install --user numpy matplotlib opencv-python;
```
Comment (qianyizh) [inline scripts/install-deps-python.sh]: Use Tab to align.

File: scripts/install-deps-python.sh [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+			source activate py36_open3d
+			conda install -y numpy matplotlib
+			conda install -y -c conda-forge opencv
+			break;;
+
+			[Qq]* )
+			# quit
+			exit;;
+
+	        * )
```
Comment (qianyizh) [inline scripts/install-deps-python.sh]: Use tab to align.

**Comment by qianyizh** [comment]
All look good to me. I am waiting for travis ci to finish.
